// <auto-generated />
using System;
using AsteriaApi.ContextFolder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsteriaApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200523092619_AddAvatarSpec")]
    partial class AddAvatarSpec
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsteriaApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AsteriaApi.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Price");

                    b.Property<int>("SpecId");

                    b.Property<TimeSpan>("Time");

                    b.Property<string>("TypeWork");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("AsteriaApi.Models.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Child");

                    b.Property<bool>("Men");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("SpecAvatar");

                    b.Property<string>("Specialization");

                    b.Property<bool>("Women");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("AsteriaApi.Models.TimeSheets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("SpecID");

                    b.Property<int>("T10m00");

                    b.Property<int>("T10m30");

                    b.Property<int>("T11m00");

                    b.Property<int>("T11m30");

                    b.Property<int>("T12m00");

                    b.Property<int>("T12m30");

                    b.Property<int>("T13m00");

                    b.Property<int>("T13m30");

                    b.Property<int>("T14m00");

                    b.Property<int>("T14m30");

                    b.Property<int>("T15m00");

                    b.Property<int>("T15m030");

                    b.Property<int>("T16m00");

                    b.Property<int>("T16m30");

                    b.Property<int>("T1700");

                    b.Property<int>("T17m30");

                    b.Property<int>("T18m00");

                    b.Property<int>("T18m30");

                    b.Property<int>("T19m00");

                    b.Property<int>("T19m30");

                    b.Property<int>("T9m00");

                    b.Property<int>("T9m30");

                    b.HasKey("Id");

                    b.ToTable("Sheetcs");
                });
#pragma warning restore 612, 618
        }
    }
}
